### ISSUE TITLE
Support for AURA USB LED Controller?

### ISSUE THREAD

**Issue by aluveitie** [liquidctl/liquidctl#249]
Any plans to support Asus AURA LED Controller which is connected through USB?

**Comment by jonasmalacofilho** [comment]
As long as someone with one of these controllers can work on the feature, merging/accepting it would be a no-brainer.

**Comment by aluveitie** [comment]
OpenRGB would have a working implementation 
https://gitlab.com/CalcProgrammer1/OpenRGB/-/tree/master/Controllers/AsusAuraUSBController

**Comment by jonasmalacofilho** [comment]
That's a good starting point.  Although, to be clear, I don't plan on working on this feature myself, at least in the short term.

**Comment by jonasmalacofilho** [comment]
This is good first issue.  Anyone interested in working on this can join our [developer's Discord server](https://discord.gg/f5HKCAadsr) for help.

**Comment by aluveitie** [comment]
There is also a working implementation for MacOS: https://github.com/notjosh/Aureal

**Comment by jonasmalacofilho** [comment]
**Triage: close without fixing**

At this time, the maintainers don't have the hardware and specifications to work on this, and no one has demonstrated interest in collaborating to get this implemented.
