### ISSUE TITLE
Missing device ID For Corsair H115i Platinum?

### ISSUE THREAD

**Issue by SamboyCoding** [liquidctl/liquidctl#250]
Hi

I'm using this software to control my NZXT Smart device and was pleasantly surprised to find that it should - in theory - also support my Corsair H115i Platinum.

However, it doesn't show up in the device list, and when I checked the [source file](https://github.com/liquidctl/liquidctl/blob/master/liquidctl/driver/hydro_platinum.py) my device ID doesn't show up.

According to that file, the device ID for a 115i Platinum is `1B1C:0C17`, but my `lsusb` reports the following:
![image](https://user-images.githubusercontent.com/7011721/103322806-a3669d80-4a37-11eb-8f85-006f371f71fd.png)

That's `1B1C:0C13`. I'm not sure if this is incorrect - as I *believe* my cooler was sold as a "Corsair H115i" (no platinum) - but I can't remember at this point.

Either way, I'm interested to see if I can get this working, as my CPU was getting rather warm earlier.

**Comment by jonasmalacofilho** [comment]
> I'm not sure if this is incorrect - as I _believe_ my cooler was sold as a "Corsair H115i" (no platinum) - but I can't remember at this point.

You're right, and this device predates the coolers actually sold as "Platinum".  As far as we know yours was sold as a H115i Pro.

See #137 and #234 to follow the work on supporting it.
