### ISSUE TITLE
Update man page to match option changes from I²C/SMBus drivers

### ISSUE THREAD

**Issue by jonasmalacofilho** [liquidctl/liquidctl#251]
At least `--non-volatile` is missing, and the how the options are organized may need to be adjusted too.

**Comment by MarshallAsch** [comment]
This is added in the man pages update in #213

**Comment by jonasmalacofilho** [comment]
Thanks!  After merging that I'll give it one last check before closing this.

**Comment by jonasmalacofilho** [comment]
All good.
