### ISSUE TITLE
[Z490 Vision D] When running liquidctl list or initialize, it doesn't list the actual LED nodes, so I can't interact.

### ISSUE THREAD

**Issue by wkruddy** [liquidctl/liquidctl#261]
Hey, maybe I'm just doing something wrong here but, I can't seem to see any LED channels
```
> liquidctl initialize all
Gigabyte RGB Fusion 2.0 5702 Controller (experimental)
├── Hardware name       IT5702-GIGABYTE V1.0.15.0
└── Firmware version                     1.0.15.0
```

According to your docs, shouldn't it also be outputting `└── LED channnels                               7` by default on this Mobo?

Running on Big Sur 11.1 ATM, Homebrew, `liquidctl 1.4.2` . 

This means I can't run any commands, or target any LED channels. Looking through the docs, I'm pretty sure I got it all? Is there some unique cable I need to connect somewhere to get access to these channels on the mobo?.. It sounds like the channels should be stock.

Thanks in advance!

**Comment by jonasmalacofilho** [comment]
The docs are outdated, the "LED channels" item was removed since it was unreliable (commit 2c24b020134989c2ffec0028586aa7bb48f4ccd4).

You should be able to just use channels `led1`, `led2`, ... `led8`.  Let me know if you get any unexpected errors.
