### ISSUE TITLE
my z73

### ISSUE THREAD

**Issue by Nawaf89** [liquidctl/liquidctl#281]
my z73 dos did not show the correct temp for gpu it shows 0 on the LCD because I have intel gpu and RTX 3080 its show the intel temp anyone knows how to fix it 
https://i.imgur.com/jdUHjh4.png
https://i.imgur.com/spCq85Y.png
https://imgur.com/eKoPgOd

**Comment by jonasmalacofilho** [comment]
This is not a support forum for CAM.
