### ISSUE TITLE
Unable to Set Color in Corsair H100i Platinum

### ISSUE THREAD

**Issue by artforlife** [liquidctl/liquidctl#294]
I am able to to control fan speeds and modes, but not control the colors. Am I doing something wrong?

```
(liquidctl) user@user-desktop:~$ sudo liquidctl status
Corsair H100i Platinum SE (experimental)
├── Liquid temperature    23.4  °C
├── Fan 1 speed            386  rpm
├── Fan 2 speed            372  rpm
└── Pump speed            2433  rpm

(liquidctl) user@user-desktop:~$ sudo liquidctl set ring color fading "hsv(0,80,100)" "hsv(180,80,100)"
ERROR: Unexpected error with Corsair H100i Platinum SE (experimental): ValueError: unsupported (channel, mode) pair, should be one of: ('led', 'super-fixed'), ('led', 'fixed'), ('led', 'off')
```

**Comment by MarshallAsch** [comment]
`ring` is not not a valid channel for that device and the `fading` mode is also not yet supported. 
See [docs/corsair-platinum-pro-xt-guide.md](https://github.com/liquidctl/liquidctl/blob/master/docs/corsair-platinum-pro-xt-guide.md) for a list of the available channels and color modes. 


There is currently a work in proges for #193 that will add support for more hardware modes, but for now there is only the ability to set static colors.
