### ISSUE TITLE
Lighting channel names not being recognized in Smart Device V2 driver

### ISSUE THREAD

**Issue by CaseySJ** [liquidctl/liquidctl#303]
** DELETE **

The problem is that my Smart Device V2 is not being recognized by macOS itself. Not a liquidctl issue.

**Comment by jonasmalacofilho** [comment]
Hi @CaseySJ, good to see you again!

The Kraken X2 coolers only have `logo`, `ring` and `sync` lighting channels ([guide](https://github.com/liquidctl/liquidctl/blob/master/docs/kraken-x2-m2-guide.md#rgb-lighting)).  Can you check if those work?

**Comment by jonasmalacofilho** [comment]
> The problem is that my Smart Device V2 is not being recognized by macOS itself. Not a liquidctl issue.

Oh, that makes sense... lighting commands intended for the SD2 were then reaching the Kraken2 driver, hence the KeyError.

**Comment by CaseySJ** [comment]
@jonasmalacofilho 

Hello again! Alas, it seems there is a fault in my Hackintosh where the Smart Device V2 is not being recognized by macOS. So I was trying to configure lighting channels for the Kraken instead of the Smart Device V2!!!

**Comment by CaseySJ** [comment]
Let me fix the Smart Device V2 (could be a hardware connection issue) and then I test see if there's any I/O error as mentioned by @sgtcoder.

Nevertheless, please close/delete this issue as it's User Error.

**Comment by jonasmalacofilho** [comment]
> and then I see if there's any I/O error as mentioned by sgtcoder.

Thanks!
