### ISSUE TITLE
Corsair Hydro H100i Platinum SE: only fans can be set to a certain speed

### ISSUE THREAD

**Issue by Lukas-drz** [liquidctl/liquidctl#343]
_(Edited by maintainer for clarity, as the H100 Platinum SE is_ not _a new device)._

When i do the following command :  sudo liquidctl set pump speed 90
I have the following return : ERROR: Unexpected error with Corsair Hydro H100i Platinum SE (experimental): ValueError: unknown channel, should be one of: 'fan', 'fan1', 'fan2'
Only fans can be set to a certain speed.

**Comment by jonasmalacofilho** [comment]
This device does not support direct pump control.

As documented in [its guide](https://github.com/liquidctl/liquidctl/blob/main/docs/corsair-platinum-pro-xt-guide.md#initializing-the-device-and-setting-the-pump-mode), you can only set a pump _mode,_ using the `initialize` command.

```
# liquidctl initialize --pump-mode quiet
# liquidctl initialize --pump-mode balanced
# liquidctl initialize --pump-mode extreme
```
