### ISSUE TITLE
Another new Product ID for NZXT'S RGB & Fan Controller

### ISSUE THREAD

**Issue by ShikiGami** [liquidctl/liquidctl#345]
I just bought a brand new NZXT "RGB & Fan Controller" and I tried to use it with liquidctl, but it wouldn't appear in the list of devices.
After looking at the issues and code, I figured out that this "RGB & Fan Controller" appears to have a brand new product ID.
![product ID: 2010](https://i.gyazo.com/24fb98ca66a2a02e59a7709988aa9e2a.png)

The new product ID appears to be "2010", and it isn't in the list of current supported devices.

**Comment by jonasmalacofilho** [comment]
This should already be fixed in our `main` branch, can you give it a try?
