### ISSUE TITLE
Error: no devices matches available drivers and selection criteria

### ISSUE THREAD

**Issue by mourke** [liquidctl/liquidctl#347]
I'm running Ubuntu 20.04 and have an NZXT H510 Elite case with an NZXT Smart Device V2. I'm using liquidctl v1.5.1.

Running `liquidctl initialize --debug` returns 

> [DEBUG] liquidctl.cli: running liquidctl v1.5.1
[DEBUG] liquidctl.driver.smbus: searching LinuxI2c (Ddr4Temperature, VengeanceRgb, EvgaPascal, RogTuring)
[DEBUG] liquidctl.driver.smbus: ignoring 0-0052, cannot infer bus number
[DEBUG] liquidctl.driver.smbus: found I²C bus i2c-3
[DEBUG] liquidctl.driver.smbus: ignoring 0-0050, cannot infer bus number
[DEBUG] liquidctl.driver.smbus: found I²C bus i2c-1
[DEBUG] liquidctl.driver.smbus: ignoring 0-0037, cannot infer bus number
[DEBUG] liquidctl.driver.smbus: found I²C bus i2c-6
[DEBUG] liquidctl.driver.smbus: found I²C bus i2c-4
[DEBUG] liquidctl.driver.smbus: found I²C bus i2c-2
[DEBUG] liquidctl.driver.smbus: found I²C bus i2c-0
[DEBUG] liquidctl.driver.smbus: ignoring 0-0036, cannot infer bus number
[DEBUG] liquidctl.driver.smbus: found I²C bus i2c-5
[DEBUG] liquidctl.driver.usb: searching HidapiBus (CommanderPro, CorsairHidPsu, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _CommonSmartDeviceDriver)
[DEBUG] liquidctl.driver.usb: found HID device 1e71:200d
[DEBUG] liquidctl.driver.usb: found HID device 0909:001c
[DEBUG] liquidctl.driver.usb: found HID device 0909:001c
[DEBUG] liquidctl.driver.usb: found HID device 1038:1720
[DEBUG] liquidctl.driver.usb: found HID device 1038:1720
[DEBUG] liquidctl.driver.usb: found HID device 1038:1720
[DEBUG] liquidctl.driver.usb: found HID device 1038:1720
[DEBUG] liquidctl.driver.usb: found HID device 1038:1720
[DEBUG] liquidctl.driver.usb: searching PyUsbBus (Hydro690Lc, Legacy690Lc, Modern690Lc, _CommonAsetekDriver)
[DEBUG] liquidctl.driver.usb: found USB device 1d6b:0003
[DEBUG] liquidctl.driver.usb: found USB device 1038:1720
[DEBUG] liquidctl.driver.usb: found USB device 1d6b:0002
[DEBUG] liquidctl.driver.usb: found USB device 1d6b:0003
[DEBUG] liquidctl.driver.usb: found USB device 1b1c:1b13
[DEBUG] liquidctl.driver.usb: found USB device 0a12:0001
[DEBUG] liquidctl.driver.usb: found USB device 0909:001c
[DEBUG] liquidctl.driver.usb: found USB device 046d:085c
[DEBUG] liquidctl.driver.usb: found USB device 05e3:0608
[DEBUG] liquidctl.driver.usb: found USB device 046d:c21f
[DEBUG] liquidctl.driver.usb: found USB device 1e71:200d
[DEBUG] liquidctl.driver.usb: found USB device 1d6b:0002
Error: no devices matches available drivers and selection criteria

`sudo lsusb` returns:

> Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 1038:1720 SteelSeries ApS Mouse
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1b1c:1b13 Corsair Vengeance K70RGB keyboard
Bus 001 Device 003: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 006: ID 0909:001c Audio-Technica Corp. AT2020USB+
Bus 001 Device 004: ID 046d:085c Logitech, Inc. C922 Pro Stream Webcam
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 008: ID 046d:c21f Logitech, Inc. F710 Wireless Gamepad [XInput Mode]
Bus 001 Device 007: ID 1e71:200d NZXT NZXT USB Device
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

and `sudo lsusb -d 1e71: -v` returns: 
````
Bus 001 Device 007: ID 1e71:200d NZXT NZXT USB Device
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1e71 NZXT
  idProduct          0x200d 
  bcdDevice            1.0c
  iManufacturer           1 NZXT. - Inc.
  iProduct                2 NZXT USB Device
  iSerial                 3 8D745268545
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     463
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered
  
````

I've looked at issue #114 and tried running `sudo rmmod usbhid && sudo modprobe usbhid` but it didn't work.

Do you know what the problem could be? I installed OpenRGB and it doesn't detect it either so it's probably something on my end but I don't know what. (I've also uninstalled OpenRGB in case that was the problem)

**Comment by mourke** [comment]
Sorry 1.5.1 isn't the latest version

**Comment by jonasmalacofilho** [comment]
That's a new `0x200d` variant of the Smart Device V2 (#338), and you'll need to use our `main` branch for now.
