### ISSUE TITLE
Hi. I wanted to install liquidctl but not shure why windows wont let me to install the .exe file. 

### ISSUE THREAD

**Issue by Roliboli24** [liquidctl/liquidctl#360]
The only way I can control my x63 trough cmd is when I cd to the excact directory of liquidctl and than all of the commands work perfectly. If I create a .bat file can I start with cd and than the commands. Will taysk schdeule automation work on startup this way too??

Thank you!

**Comment by jonasmalacofilho** [comment]
That's the correct usage, at least for now: we don't release an installer, but, rather, just the zipped `liquidctl` executable.  That's usually referred to as a "portable" executable.

Everything should work fine, including Task Scheduler, as long as you place `liquidctl.exe` on a directory already on your `PATH` environment variable, or you add the new directory to that variable.
