### ISSUE TITLE
Corsair Hydro H150i Pro XT (Not a bug but a typo from my end)

### ISSUE THREAD

**Issue by shadyslim2018** [liquidctl/liquidctl#374]
**Affected device:** Corsair Hydro H150i Pro XT 
**Operating system:** Manjaro Linux
**Liquidctl version:** liquidctl v1.7.1 (Arch User Repository; liquidctl-git 1.7.1.r9.cb44a66-1)

Eveything's working fine except for `liquidctl --match Corsair initialize --pump-mode quite`
                                                                  
**Error message:** `ERROR: Unexpected error with Corsair Hydro H150i Pro XT (experimental): KeyError: 'QUITE'`

**Comment by perru** [comment]
Maybe it's "quiet" and not "quite" ?

**Comment by shadyslim2018** [comment]
I can't believe I made such a mistake. Thank you correcting my error.
