### ISSUE TITLE
Integration with freon not working

### ISSUE THREAD

**Issue by dirusulixes** [liquidctl/liquidctl#378]
Hi, 

I'm trying to have [freon](https://github.com/UshakovVasilii/gnome-shell-extension-freon) read liquidctrl sensors. I initialise with the `--json` argument as a service:

```
[Unit]
Description=AIO startup service

[Service]
Type=oneshot
ExecStart=liquidctl initialize all --json
ExecStart=liquidctl --match kraken set pump speed 90
ExecStart=liquidctl --match kraken set fan speed  30 50  35 60  40 90  50 100

[Install]
WantedBy=default.target
```

The sensors are not list in the freon dropdown.

Additional information about the system:

- Affected device: NZXT Kraken Z (Z53)
- Operating system: Arch Linux
- Liquidctl version: Arch Linux liquidctl package, version 1.7.1-1

**Comment by jonasmalacofilho** [comment]
Have you enabled "Show liquidctl sensors" in the Freon settings?

And you don't have to initialize with `--json`.

**Comment by dirusulixes** [comment]
thanks and sorry for wasting your time. Turns out that the latest release of freon is older then I had realised. Using the latest version of the code I see the option and it all works fine.

**Comment by jonasmalacofilho** [comment]
That's ok! : )
