### ISSUE TITLE
Windows XP support?

### ISSUE THREAD

**Issue by Wasmachineman-NL** [liquidctl/liquidctl#386]
I have a NZXT E500 in my Pentium M XP rig and I was wondering: can I use liquidctl to check what amount of power my E500 is using, under XP with something like HWiNFO?

**Comment by jonasmalacofilho** [comment]
> I have a NZXT E500 in my Pentium M XP rig and I was wondering: can I use liquidctl to check what amount of power my E500 is using, under XP

Probably, although some of our dependencies may not support XP anymore.

> with something like HWiNFO?

What do you mean?  Using the [LQiNFO script](https://github.com/liquidctl/liquidctl/blob/main/extra/windows/LQiNFO.py) for supplying HWiNFO with liquidctl data?

**Comment by Wasmachineman-NL** [comment]
I guess so, NZXT CAM doesn't run under XP obviously.

**Comment by jonasmalacofilho** [comment]
Well, it turns out that our minimum Python 3 required version (3.6) already does _not_ run on Windows XP.

---

Can I ask what are you using a desktop/home server Pentium M platform running Windows XP for these days?

**Comment by MarshallAsch** [comment]
> Can I ask what you are using a desktop/home server Pentium M platform running Windows XP for these days?

Im curious about the answer to this too

**Comment by Wasmachineman-NL** [comment]
Partially based on my first computer I had back in 2003 (that had a Pentium 4 though), I mostly use it for older games.

**Comment by jonasmalacofilho** [comment]
Oh, cool!

---

Well, sorry we can't support Windows XP.

You could connect the PSU data to another machine (even something like a Raspberry Pi) and monitor it from there...
