### ISSUE TITLE
Staggered temperatures are not supported by NZXT RGB & Fan Controller

### ISSUE THREAD

**Issue by BlownIntoSpace** [liquidctl/liquidctl#389]
When trying to set the fan speed for the NZXT RGB & Fan Controller, it only lets me set a single percentile value for fan speed.
e.g. `set fan1 speed  50`

Staggered fan speeds such as `set fan1 speed  20 30  30 50  34 80  40 90  50 100` returns the error "`ERROR: Error: operation not supported by NZXT RGB & Fan Controller`". The official NZXT software supports this feature, so it is not a limitation of the hardware, to my knowledge.

**Comment by jonasmalacofilho** [comment]
CAM supports it at the software level, but that hardware does not.  The main limitation is that the controller does not have any temperature sensors, and it cannot by itself access other sensors on the system.

Similar functionality has been implemented as a script on top of the liquidctl APIs, [`extra/yoda`](https://github.com/liquidctl/liquidctl/blob/main/extra/yoda), but the part about grabbing temperature data from the system has so far only been implemented for Linux and, to a lesser extent, Mac OS.
