### ISSUE TITLE
Kraken X42 not recognized in liquidctl > v1.3.2

### ISSUE THREAD

**Issue by JojoBie** [liquidctl/liquidctl#396]
I recognized some while ago newer versions of liquidctl does not recognize my Kraken x42 anymore.
version v1.3.2 did well.

python3 -m /liquidctl.cli --version; python3 -m liquidctl.cli list --verbose 

liquidctl v1.3.2 (fb9ec1fdb0ce-dirty):
Device ID 0: NZXT Kraken X (X42, X52, X62 or X72)
├── Vendor ID: 0x1e71
├── Product ID: 0x170e
├── Release number: 0x0200
├── Serial number: XXXYYYYZZZZ
├── Bus: usb1
├── Address: 4
├── Port: 7
└── Driver: KrakenTwoDriver using module usb

but no device found in v.1.7.2!!!

liquidctl v1.7.2 (2b4376891c2d):
\<no output\>

**Comment by jonasmalacofilho** [comment]
Are you on Windows and, if you so, did you ever use Zadig (or some other tool) to replace the stock Windows driver?

**Comment by JojoBie** [comment]
----------------------------------------------------------------------------------------------------------------
# /usr/src/liquidctl_1_3_2# python3 -m /liquidctl.cli list --debug

[DEBUG] __main__: running liquidctl v1.3.2 (fb9ec1fdb0ce-dirty)
[DEBUG] liquidctl.driver.usb: searching GenericHidBus (api=usb, drivers=[CommonSmartDeviceDriver, CorsairHidPsuDriver, KrakenTwoDriver, SeasonicEDriver, SmartDeviceDriver, SmartDeviceV2Driver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x174c:0x3074
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1e71:0x170e
[DEBUG] liquidctl.driver.usb: instanced driver for NZXT Kraken X (X42, X52, X62 or X72)
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0x1b2d
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0xa18
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x174c:0x2074
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0x1b3e
[DEBUG] liquidctl.driver.usb: probing drivers for device 0xb05:0x1867
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: searching PyUsbBus (drivers=[AsetekDriver, CommonAsetekDriver, CorsairAsetekDriver, LegacyAsetekDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x174c:0x3074
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x3
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1e71:0x170e
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0x1b2d
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0xa18
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x174c:0x2074
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1b1c:0x1b3e
[DEBUG] liquidctl.driver.usb: probing drivers for device 0xb05:0x1867
[DEBUG] liquidctl.driver.usb: probing drivers for device 0x1d6b:0x2
Device ID 0: NZXT Kraken X (X42, X52, X62 or X72)
├── Vendor ID: 0x1e71
├── Product ID: 0x170e
├── Release number: 0x0200
├── Serial number: 5D85146B343
├── Bus: usb1
├── Address: 4
├── Port: 7
└── Driver: KrakenTwoDriver using module usb
[DEBUG] __main__: hierarchy: UsbHidDriver, BaseUsbDriver, BaseDriver; PyUsbHid

-----------------------------------------------------------------------------------------------------------------
# >/usr/src/liquidctl# python3 -m /liquidctl.cli list --debug

[DEBUG] cli (main): running liquidctl v1.7.2 (2b4376891c2d)
[DEBUG] smbus (find_devices): searching LinuxI2c (Ddr4Temperature, VengeanceRgb, EvgaPascal, RogTuring)
[DEBUG] smbus (find_devices): found I²C bus i2c-3
[DEBUG] smbus (find_devices): found I²C bus i2c-10
[DEBUG] smbus (find_devices): found I²C bus i2c-1
[DEBUG] smbus (find_devices): found I²C bus i2c-17
[DEBUG] smbus (find_devices): found I²C bus i2c-8
[DEBUG] smbus (find_devices): found I²C bus i2c-15
[DEBUG] smbus (find_devices): found I²C bus i2c-6
[DEBUG] smbus (find_devices): found I²C bus i2c-13
[DEBUG] smbus (find_devices): found I²C bus i2c-4
[DEBUG] smbus (find_devices): found I²C bus i2c-11
[DEBUG] smbus (find_devices): found I²C bus i2c-2
[DEBUG] smbus (find_devices): found I²C bus i2c-0
[DEBUG] smbus (find_devices): found I²C bus i2c-9
[DEBUG] smbus (find_devices): found I²C bus i2c-16
[DEBUG] smbus (find_devices): found I²C bus i2c-7
[DEBUG] smbus (find_devices): found I²C bus i2c-14
[DEBUG] smbus (find_devices): found I²C bus i2c-5
[DEBUG] smbus (find_devices): found I²C bus i2c-12
[DEBUG] usb (find_devices): searching HidapiBus (CommanderCore, CommanderPro, CorsairHidPsu, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _CommonSmartDeviceDriver)
[DEBUG] usb (find_devices): found HID device 0b05:1867
[DEBUG] usb (find_devices): found HID device 1b1c:1b3e
[DEBUG] usb (find_devices): found HID device 1b1c:1b3e
[DEBUG] usb (find_devices): found HID device 1b1c:1b3e
[DEBUG] usb (find_devices): found HID device 1b1c:1b3e
[DEBUG] usb (find_devices): found HID device 1b1c:1b3e
[DEBUG] usb (find_devices): found HID device 1b1c:1b3e
[DEBUG] usb (find_devices): found HID device 1b1c:1b3e
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:0a18
[DEBUG] usb (find_devices): found HID device 1b1c:1b2d
[DEBUG] usb (find_devices): found HID device 1b1c:1b2d
[DEBUG] usb (find_devices): found HID device 1b1c:1b2d
[DEBUG] usb (find_devices): found HID device 1b1c:1b2d
[DEBUG] usb (find_devices): found HID device 1b1c:1b2d
[DEBUG] usb (find_devices): found HID device 1b1c:1b2d
[DEBUG] usb (find_devices): found HID device 1b1c:1b2d
[DEBUG] usb (find_devices): searching PyUsbBus (Hydro690Lc, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc, CorsairAsetekProDriver)
[DEBUG] usb (find_devices): found USB device 1d6b:0002
[DEBUG] usb (find_devices): found USB device 1d6b:0003
[DEBUG] usb (find_devices): found USB device 1d6b:0003
[DEBUG] usb (find_devices): found USB device 1d6b:0002
[DEBUG] usb (find_devices): found USB device 1d6b:0003
[DEBUG] usb (find_devices): found USB device 1d6b:0002
[DEBUG] usb (find_devices): found USB device 174c:3074
[DEBUG] usb (find_devices): found USB device 1d6b:0003
[DEBUG] usb (find_devices): found USB device 1e71:170e   <---- doesnt take this
[DEBUG] usb (find_devices): found USB device 1b1c:1b2d
[DEBUG] usb (find_devices): found USB device 1b1c:0a18
[DEBUG] usb (find_devices): found USB device 174c:2074
[DEBUG] usb (find_devices): found USB device 1b1c:1b3e
[DEBUG] usb (find_devices): found USB device 0b05:1867
[DEBUG] usb (find_devices): found USB device 1d6b:0002

-----------------------------------------------------------------------------------------------------------------

# lsusb -d1e71:170e -v

Bus 001 Device 004: ID 1e71:170e NZXT Kraken X
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x1e71 NZXT
  idProduct          0x170e Kraken X
  bcdDevice            2.00
  iManufacturer           1 NZXT.-Inc.
  iProduct                2 NZXT USB Device
  iSerial                 3 5D85146B343
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     174
          Report Descriptor: (length is 174)
            Item(Global): Usage Page, data= [ 0x00 0xff ] 65280
                            (null)
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Global): Report ID, data= [ 0x01 ] 1
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x01 ] 1
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x01 ] 1
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Output, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x02 ] 2
            Item(Local ): Usage, data= [ 0x02 ] 2
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x40 ] 64
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x02 ] 2
            Item(Local ): Usage, data= [ 0x02 ] 2
                            (null)
            Item(Main  ): Output, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x03 ] 3
            Item(Local ): Usage, data= [ 0x03 ] 3
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x40 ] 64
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x03 ] 3
            Item(Local ): Usage, data= [ 0x03 ] 3
                            (null)
            Item(Main  ): Output, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0xf0 ] 240
            Item(Local ): Usage, data= [ 0x04 ] 4
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x40 ] 64
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0xf0 ] 240
            Item(Local ): Usage, data= [ 0x04 ] 4
                            (null)
            Item(Main  ): Output, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x10 ] 16
            Item(Local ): Usage, data= [ 0x05 ] 5
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x40 ] 64
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x10 ] 16
            Item(Local ): Usage, data= [ 0x05 ] 5
                            (null)
            Item(Main  ): Output, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x12 ] 18
            Item(Local ): Usage, data= [ 0x06 ] 6
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x40 ] 64
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x12 ] 18
            Item(Local ): Usage, data= [ 0x06 ] 6
                            (null)
            Item(Main  ): Output, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0xf1 ] 241
            Item(Local ): Usage, data= [ 0x07 ] 7
                            (null)
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x3f ] 63
            Item(Main  ): Input, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x11 ] 17
            Item(Local ): Usage, data= [ 0x08 ] 8
                            (null)
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x3f ] 63
            Item(Main  ): Input, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x04 ] 4
            Item(Local ): Usage, data= [ 0x09 ] 9
                            (null)
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x10 ] 16
            Item(Main  ): Input, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x13 ] 19
            Item(Local ): Usage, data= [ 0x0a ] 10
                            (null)
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x3f ] 63
            Item(Main  ): Input, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
  
-----------------------------------------------------------------------------------------------------------------  
  
# lsusb -tvv

/:  Bus 10.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/  /dev/bus/usb/010/001
/:  Bus 09.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    /sys/bus/usb/devices/usb9  /dev/bus/usb/009/001
/:  Bus 08.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/  /dev/bus/usb/008/001
/:  Bus 07.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    /sys/bus/usb/devices/usb7  /dev/bus/usb/007/001
/:  Bus 06.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/  /dev/bus/usb/006/001
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    /sys/bus/usb/devices/usb5  /dev/bus/usb/005/001
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/10p, 5000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/usb2  /dev/bus/usb/002/001
    |__ Port 6: Dev 2, If 0, Class=Hub, Driver=hub/4p, 5000M
        ID 174c:3074 ASMedia Technology Inc. ASM1074 SuperSpeed hub
        /sys/bus/usb/devices/2-6  /dev/bus/usb/002/002
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/16p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    /sys/bus/usb/devices/usb1  /dev/bus/usb/001/001
    |__ Port 5: Dev 2, If 1, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1b1c:1b3e Corsair
        /sys/bus/usb/devices/1-5  /dev/bus/usb/001/002
    |__ Port 5: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1b1c:1b3e Corsair
        /sys/bus/usb/devices/1-5  /dev/bus/usb/001/002
    |__ Port 6: Dev 3, If 0, Class=Hub, Driver=hub/4p, 480M
        ID 174c:2074 ASMedia Technology Inc. ASM1074 High-Speed hub
        /sys/bus/usb/devices/1-6  /dev/bus/usb/001/003
        |__ Port 2: Dev 5, If 0, Class=Audio, Driver=snd-usb-audio, 12M
            ID 1b1c:0a18 Corsair
            /sys/bus/usb/devices/1-6.2  /dev/bus/usb/001/005
        |__ Port 2: Dev 5, If 3, Class=Human Interface Device, Driver=usbhid, 12M
            ID 1b1c:0a18 Corsair
            /sys/bus/usb/devices/1-6.2  /dev/bus/usb/001/005
        |__ Port 2: Dev 5, If 1, Class=Audio, Driver=snd-usb-audio, 12M
            ID 1b1c:0a18 Corsair
            /sys/bus/usb/devices/1-6.2  /dev/bus/usb/001/005
        |__ Port 2: Dev 5, If 2, Class=Audio, Driver=snd-usb-audio, 12M
            ID 1b1c:0a18 Corsair
            /sys/bus/usb/devices/1-6.2  /dev/bus/usb/001/005
        |__ Port 3: Dev 7, If 0, Class=Human Interface Device, Driver=usbhid, 12M
            ID 1b1c:1b2d Corsair K95 RGB Platinum Keyboard [RGP0056]
            /sys/bus/usb/devices/1-6.3  /dev/bus/usb/001/007
        |__ Port 3: Dev 7, If 1, Class=Human Interface Device, Driver=usbhid, 12M
            ID 1b1c:1b2d Corsair K95 RGB Platinum Keyboard [RGP0056]
            /sys/bus/usb/devices/1-6.3  /dev/bus/usb/001/007
    |__ Port 7: Dev 4, If 0, Class=Human Interface Device, Driver=, 12M
        ID 1e71:170e NZXT Kraken X
        /sys/bus/usb/devices/1-7  /dev/bus/usb/001/004
    |__ Port 14: Dev 6, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 0b05:1867 ASUSTek Computer, Inc.
        /sys/bus/usb/devices/1-14  /dev/bus/usb/001/006  

-----------------------------------------------------------------------------------------------------------------

**Comment by JojoBie** [comment]
i'am sorry... just saw i patched the 1.3.2 version using the deprecated option "--hid=usb".
so it's the version-change using libhidapi-hidraw you mentioned!

**Comment by JojoBie** [comment]
any suggestion how i can get this with libhidapi-hidraw running?

**Comment by JojoBie** [comment]
X42 doesn't bind to an usbhid driver... Don't know why. Did not find any udev-rules that might block this.
:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/16p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    /sys/bus/usb/devices/usb1  /dev/bus/usb/001/001
    |__ ...
    |__ Port 5: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1b1c:1b3e Corsair
        /sys/bus/usb/devices/1-5  /dev/bus/usb/001/002
    |__ Port 6: Dev 3, If 0, Class=Hub, Driver=hub/4p, 480M
		...
		...
        |__ Port 3: Dev 7, If 1, Class=Human Interface Device, Driver=usbhid, 12M
            ID 1b1c:1b2d Corsair K95 RGB Platinum Keyboard [RGP0056]
            /sys/bus/usb/devices/1-6.3  /dev/bus/usb/001/007
    |__ Port 7: Dev 4, If 0, Class=Human Interface Device, Driver=, 12M
        ID 1e71:170e NZXT Kraken X
        /sys/bus/usb/devices/1-7  /dev/bus/usb/001/004

**Comment by jonasmalacofilho** [comment]
> any suggestion how i can get this with libhidapi-hidraw running?

Bind the device to the `usbhid` driver and/or prevent it from being left unbound by other tools or even old liquidctl.

---

> X42 doesn't bind to an usbhid driver... Don't know why. Did not find any udev-rules that might block this.

Can you attach (or send me) your kernel log for one session?

**Comment by JojoBie** [comment]
changed usb-port and cable. no effect. perhaps a problem with the x42-usb-interface itself. log via email.

**Comment by jonasmalacofilho** [comment]
> log via email.

Got it, thanks.

> perhaps a problem with the x42-usb-interface itself

Doesn't look like it.  Perhaps a kernel bug?

This could also be related to the use of Proxmox; I also maintain PyUSB, and a weird issue has popped up there which appears to be caused by Proxmox.

I'm not sure how detailed the debug output from the usb and hid subsystems are by default, but can you try enabling it?  There's the `debug=1` boot parameter, and you also probably have access to [dynamic debug](https://www.kernel.org/doc/html/latest/admin-guide/dynamic-debug-howto.html).

**Comment by jonasmalacofilho** [comment]
Of course, I'm assuming you haven't blacklisted any modules that could affect that device.

Also, I would expect the `nzxt_kraken2` driver to bind to the device as well on Linux 5.13+.  But maybe it has been configured out of that particular kernel build?
