### ISSUE TITLE
FR: Yoda for windows

### ISSUE THREAD

**Issue by truglodite** [liquidctl/liquidctl#398]
I'm after CPU temps in liquidctl... using windows. Coding for this is above my head, but I did try yoda on my windows rig and it just showed liquid temps. Saw info on how to get mac and linux working with yoda. 

How about windows? Is this a rabbit hole nobody has entered yet?

I would love to contribute, but coding for this is going to be well above my head. Otherwise, I'm loving liquidctl for controlling my x73 and lightning core. It's just that with CPU temp input, well y'know... I could make it even quieter than it is now.

**Comment by jonasmalacofilho** [comment]
It's certainly a rabbit hole...

I looked into it a while back, and it was a mess.  We could:

- use the Intel and AMD dlls directly, but we would need to write Python wrappers and figure out how to distribute them;
- write our own monitor directly using specific CPU MSRs, but that would be hard to test and keep up to date with new models;
- use HWiNFO, which supports virtually every CPU and motherboard out there, but is proprietary;
- use some open source hardware monitoring SDK, but at the time there wasn't any that was actively maintained (plus, IIRC, OpenHardwareMonitor uses C#, and I don't know how to integrate that with Python).

That was a long time ago though, so it's possible that things have improved.
