### ISSUE TITLE
Support the project

### ISSUE THREAD

**Issue by WMcKibbin** [liquidctl/liquidctl#409]
Please describe the issue or request as clearly and completely as possible.
I would like to give support to the liquidctl project with a https://www.buymeacoffee.com/ or patreon or github sponsorship. Do you guys have any such mechanism in place? I just bought a nice new liquid cooler which is going to be controlled through this software. Would like to say thankyou somehow. 

Thanks!

**Comment by jonasmalacofilho** [comment]
Hey, thanks for wanting to support the project!

At the org level, setting up something (probably through Open Collective) is on my to-do list.

At the personal level I thought GitHub Sponsors would be working for me by now, but it took a while to even be enabled in my region... now my application is "pending review."  In the meantime, I guess I should create a Patreon for myself; once I do, I'll drop a link to it here.

**Comment by WMcKibbin** [comment]
Awesome, drop me those links when you can!

**Comment by jonasmalacofilho** [comment]
I added a [FUNDING.md](https://github.com/liquidctl/liquidctl/blob/main/FUNDING.md) document with various ways to support the liquidctl maintainers, and also enabled the "Sponsor" button here on GitHub (pointing to that same document).
