### ISSUE TITLE
LCD screen on NZXT Kraken Z coolers

### ISSUE THREAD

**Issue by jonasmalacofilho** [liquidctl/liquidctl#444]
liquidctl has had support for basic monitoring and fan/pump control of NZXT Kraken Z coolers for a while, but the LCD screen continues to a thorn, and very little progress has been made regarding a concrete driver implementation.  This issue replaces #79, which was getting quite long despite being stalled and not containing much technical information.

Device type: LCD screen embedded in AIO liquid cooler
Product page: https://nzxt.com/collection/kraken-z
First-party software: NZXT CAM
Other commonly used tools: [KrakenZPlayground](https://github.com/ProtozeFOSS/KrakenZPlayground)

The device appears to support the following features:

 - monitoring of temperatures or other environment sensors: already supported
 - monitoring of fan or pump speeds or duty cycles:  already supported
 - configurable fan or pump speeds: already supported
 - configurable lighting of accessories like RGB fans or LED strips: already supported
 - _configurable LCD screen: frame buffer and on-device GIFs_

The device is physically connected to the host system using:

- USB

The device uses which protocols to communicate with the host system:

- HID
- USB (secondary non-HID interface)

Additional information about the device:

- [[GitHub] lsusb output and a few USB traffic captures](https://github.com/liquidctl/collected-device-data)
- [[Discord] initial analysis of the screen protocol (see pinned messages)](https://discord.com/channels/780568774964805672/807357238217801774)
- [[GitHub] third-party open-source implementation: KrakenZPlayground](https://github.com/ProtozeFOSS/KrakenZPlayground)

---

Please stick to [reacting](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to this first comment if you just want to communicate your interest in the feature.  Similarly, if you just want get updates about this issue, subscribe to the thread by clicking the appropriate button on the right.  We also already have a surplus of testing volunteers, so there's no need to comment offering more of that either.

On the other hand, what we very much need right now is someone with one of these devices to, with help from the maintainers, get the driver implementation started and tested.

**Comment by mdeguzis** [comment]
User here with a Z64 and a strong Linux background. Available for testing, logs, and feedback.  Currently running ChimeraOS / Arch Linux.

**Comment by dragonifnotifiswat** [comment]
Hello
I got  a z53 Kraken running on arch, I'm a bit familiar with python as well. 

I'd like to see this run let me know if you need any info.
