### ISSUE TITLE
Corsair Comander Core: lights flash with every update

### ISSUE THREAD

**Issue by arch-user-france1** [liquidctl/liquidctl#448]
The RGB lights flash _once_ per request (eg. `liquidctl status`).

Additional information about the system:

- Operating system and version: Manjaro Linux
- Liquidctl installation method: yay
- version: 1.8.1

**Comment by jonasmalacofilho** [comment]
Cc: @ParkerMc

**Comment by jonasmalacofilho** [comment]
I'm pretty sure this is a known problem, but it seems we still didn't have an issue open for it.  Thanks for reporting it.

**Comment by ParkerMc** [comment]
That is correct. It is unknown at the moment if it fixable, but it wouldn't hurt to keep an issue open for now to track it.
Quick background, it happens when we "wake up" the controller, that puts it in software mode and somewhere in that it turns off the leds that get turned back on when it falls back to hardware mode.
It is possible that the issue will go away for all but the first time if we copy the hardware mode RGB to the software RGB, but it will likely restart the animation.

**Comment by ParkerMc** [comment]
There is currently no path to fixing this as liquidctl only supports hardware mode.

**Comment by jonasmalacofilho** [comment]
On Linux, specifically, and _if_ someone writes the kernel driver for it, a hwmon driver for this device could be a solution: it would both keep device in software mode, as well as already provide status information in a convenient form.

(Liquidctl can be made to fetch info from hwmon, when thats's available... we're already doing that on other devices that have those kernel drivers).

**Comment by jonasmalacofilho** [comment]
Triage: closing as, like ParkerMc said, there's currently no path to fixing this _in liquidctl._

**Comment by Viktini** [comment]
Would this affect software that puts the lights in software mode? Apparently [OpenRGB supports the Commander Core controllers](https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/3008) so I thought I'd ask.

**Comment by arch-user-france1** [comment]
It would not, I think.

**Comment by ParkerMc** [comment]
> Would this affect software that puts the lights in software mode? Apparently [OpenRGB supports the Commander Core controllers](https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/3008) so I thought I'd ask.

I also implemented the OpenRGB controller. And no it will not. But the OpenRGB controller has to always be running.(I also wrote that one)
