### ISSUE TITLE
Does --temp-probe not work?

### ISSUE THREAD

**Issue by Sc0th** [liquidctl/liquidctl#494]
---
```
Corsair Commander Pro
├── Temperature 1     30.9  °C
├── Temperature 2     27.0  °C
├── Fan 1 speed        672  rpm
├── +12V rail        12.07  V
├── +5V rail          5.01  V
└── +3.3V rail        3.39  V
```
trying to set a profile based on probe does not appear to play nice:

```
[INF] infra01:~#liquidctl set fan1 speed 30 500 35 1500 --temp-probe 1
Usage:
  liquidctl [options] list
  liquidctl [options] initialize [all]
  liquidctl [options] status
  liquidctl [options] set <channel> speed (<temperature> <percentage>) ...
  liquidctl [options] set <channel> speed <percentage>
  liquidctl [options] set <channel> color <mode> [<color>] ...
  liquidctl --help
  liquidctl --version
[INF] infra01:~#
```

works fine without the probe setting

Additional information about the system:

- Affected device(s): 
Device #0: Corsair Commander Pro

- Operating system and version: 
AlmaLinux 8.6 (Sky Tiger)

- Liquidctl installation method: 
pip3 install

- Output of `liquidctl --version`: 
liquidctl v1.10.0 (Linux-4.18.0-372.19.1.el8_6.x86_64-x86_64-with-almalinux-8.6-Sky_Tiger)

**Comment by jonasmalacofilho** [comment]
That was a documentation bug: the correct option name is `--temperature-sensor`.  Fixed in `main`.
