### ISSUE TITLE
ERROR: unexpected OS error with Corsair HYdro H115i Platinum: OSError('Could not write to device')

### ISSUE THREAD

**Issue by HeathenHacks** [liquidctl/liquidctl#546]
### Describe the bug

I'm using Coolero to control my AIO and fan's speed and liquidctl is one of it's dependencies.

I'm using an Arch-derivative distro called "ArcoLinux" with KDE Plasma as my WM.

Earlier today, after I booted up my PC and logged in, I received a notification from Coolero that's says:

### Device Communication Issue

**Liquidctl** has detected a communication problem with your device.

This is most likely due to permissions issue when accessing devices **not** as root.

To give your user access to the system's USB devices you can apply some udev rules.

![Screenshot_20221218_193655](https://user-images.githubusercontent.com/43103175/208296329-8b35e1c5-deba-4416-bab4-668b3758971f.png)

-------------------------------------------------------------------------------------------------------------------------------------------------------------

So, I clicked on **Do it**, then restarted my PC.

But, after logging in, I received the same notification.

So, I checked on liquidctl via the terminal.

I entered `liquidctl status`

Then, it showed the unexpected OS error.

![Screenshot_20221218_194313](https://user-images.githubusercontent.com/43103175/208296467-c7a84e46-4476-4295-a4d7-b1b36f10aab9.png)
-------------------------------------------------------------------------------------------------------------------------------------------------------------

It can detect my Commander Pro just fine, but it's having a problem with my AIO.

Just happened today as well.

Thanks!

### Commands executed

`$ liquidctl status`
`$ liquidctl initialize all`

### Output of all relevant commands with `--debug` flag

$ liquidctl status --debug
[DEBUG] (cli) (main): script: /usr/bin/liquidctl
[DEBUG] (cli) (main): version: 1.11.1
[DEBUG] (cli) (main): platform: Linux-6.0.12-arch1-1-x86_64-with-glibc2.36
[DEBUG] (cli) (_log_requirements): python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
[DEBUG] (cli) (_log_requirements): colorlog: 6.7.0
[DEBUG] (cli) (_log_requirements): crcmod: 1.7
[DEBUG] (cli) (_log_requirements): docopt: 0.6.2
[DEBUG] (cli) (_log_requirements): hidapi: 0.12.0.post2
[DEBUG] (cli) (_log_requirements): pyusb: 1.2.1
[DEBUG] (cli) (_log_requirements): pillow: 9.3.0
[DEBUG] (cli) (_log_requirements): smbus: 1.1
[DEBUG] (cli) (_log_requirements): winusbcdc: version n/a (No package metadata was found for winusbcdc)
[DEBUG] (cli) (_log_requirements): libusb-package: version n/a (No package metadata was found for libusb-package)
[DEBUG] (smbus) (find_devices): searching LinuxI2c
[DEBUG] (smbus) (find_devices): LinuxI2c drivers: Ddr4Temperature, EvgaPascal, RogTuring, VengeanceRgb
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-3
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-1
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-6
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-4
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-2
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-0
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-7
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0008 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-5
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: Aquacomputer, AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 048d:8297 (usage_page=0xff89 usage=0x0010)
[DEBUG] (usb) (find_devices): HID device: 048d:8297 (usage_page=0xff89 usage=0x00cc)
[DEBUG] (usb) (probe): RgbFusion2 identified: Gigabyte RGB Fusion 2.0 8297 Controller
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c0b (usage_page=0xffc0 usage=0x0001)
[DEBUG] (usb) (probe): CommanderPro identified: Corsair Lighting Node Pro
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c17 (usage_page=0xff00 usage=0x0001)
[DEBUG] (hydro_platinum) (probe): HydroPlatinum identified: Corsair Hydro H115i Platinum
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c10 (usage_page=0x0084 usage=0x0052)
[DEBUG] (usb) (__init__): has kernel driver: corsair-cpro (/sys/class/hidraw/hidraw6/device/hwmon/hwmon4)
[DEBUG] (usb) (probe): CommanderPro identified: Corsair Commander Pro
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1b1c:1b49
[DEBUG] (usb) (find_devices): USB device: 248a:8368
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 8087:0029
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c10
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c17
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c0b
[DEBUG] (usb) (find_devices): USB device: 05e3:0610
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 048d:8297
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (cli) (main): device: Gigabyte RGB Fusion 2.0 8297 Controller
[INFO] (rgb_fusion2) (get_status): status reports not available from Gigabyte RGB Fusion 2.0 8297 Controller
[DEBUG] (cli) (main): device: Corsair Lighting Node Pro
[DEBUG] (keyval) (__init__): data in /run/user/1000/liquidctl/vid1b1c_pid0c0b/loc5
[DEBUG] (commander_pro) (get_status): only Commander Pro and Obsidian 1000D report status
[DEBUG] (cli) (main): device: Corsair Hydro H115i Platinum
[DEBUG] (keyval) (__init__): data in /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2
[DEBUG] (keyval) (load_store): loaded sequence=6 (from /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2/sequence)
[DEBUG] (keyval) (load_store): replaced with sequence=7 (stored in /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2/sequence)
[DEBUG] (usb) (clear_enqueued_reports): discarded 0 previously enqueued reports
[DEBUG] (usb) (write): writting report 0x00 with 64 bytes: 3f:38:ff:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01
[INFO] (cli) (log): detailed error: unexpected OS error with Corsair Hydro H115i Platinum: OSError('Could not write to device')
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/liquidctl/cli.py", line 466, in main
    status = dev.get_status(**opts)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/hydro_platinum.py", line 227, in get_status
    res = self._send_command(_FEATURE_COOLING, _CMD_GET_STATUS)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/hydro_platinum.py", line 379, in _send_command
    self.device.write(buf)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/usb.py", line 480, in write
    raise OSError('Could not write to device')
OSError: Could not write to device
[ERROR] (cli) (log): unexpected OS error with Corsair Hydro H115i Platinum: OSError('Could not write to device')
[DEBUG] (cli) (main): device: Corsair Commander Pro
[DEBUG] (keyval) (__init__): data in /run/user/1000/liquidctl/vid1b1c_pid0c10/loc6
[INFO] (commander_pro) (get_status): bound to corsair-cpro kernel driver, reading status from hwmon
[DEBUG] (keyval) (load): loaded temp_sensors_connected=[1, 1, 1, 1] (from /run/user/1000/liquidctl/vid1b1c_pid0c10/loc6/temp_sensors_connected)
[DEBUG] (keyval) (load): loaded fan_modes=[2, 2, 2, 2, 0, 0] (from /run/user/1000/liquidctl/vid1b1c_pid0c10/loc6/fan_modes)
[DEBUG] (hwmon) (get_string): read temp1_input: 27120
[DEBUG] (hwmon) (get_string): read temp2_input: 33100
[DEBUG] (hwmon) (get_string): read temp3_input: 35200
[DEBUG] (hwmon) (get_string): read temp4_input: 33350
[DEBUG] (hwmon) (get_string): read fan1_input: 1520
[DEBUG] (hwmon) (get_string): read fan2_input: 1492
[DEBUG] (hwmon) (get_string): read fan3_input: 1488
[DEBUG] (hwmon) (get_string): read fan4_input: 1492
[DEBUG] (hwmon) (get_string): read in0_input: 11883
[DEBUG] (hwmon) (get_string): read in1_input: 4857
[DEBUG] (hwmon) (get_string): read in2_input: 3284
Corsair Commander Pro
├── Temperature 1     27.1  °C
├── Temperature 2     33.1  °C
├── Temperature 3     35.2  °C
├── Temperature 4     33.4  °C
├── Fan 1 speed       1520  rpm
├── Fan 2 speed       1492  rpm
├── Fan 3 speed       1488  rpm
├── Fan 4 speed       1492  rpm
├── +12V rail        11.88  V
├── +5V rail          4.86  V
└── +3.3V rail        3.28  V

-------------------------------------------------------------------------------------------------------------------------------------------------------------

$ liquidctl initialize all --debug
[DEBUG] (cli) (main): script: /usr/bin/liquidctl
[DEBUG] (cli) (main): version: 1.11.1
[DEBUG] (cli) (main): platform: Linux-6.0.12-arch1-1-x86_64-with-glibc2.36
[DEBUG] (cli) (_log_requirements): python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
[DEBUG] (cli) (_log_requirements): colorlog: 6.7.0
[DEBUG] (cli) (_log_requirements): crcmod: 1.7
[DEBUG] (cli) (_log_requirements): docopt: 0.6.2
[DEBUG] (cli) (_log_requirements): hidapi: 0.12.0.post2
[DEBUG] (cli) (_log_requirements): pyusb: 1.2.1
[DEBUG] (cli) (_log_requirements): pillow: 9.3.0
[DEBUG] (cli) (_log_requirements): smbus: 1.1
[DEBUG] (cli) (_log_requirements): winusbcdc: version n/a (No package metadata was found for winusbcdc)
[DEBUG] (cli) (_log_requirements): libusb-package: version n/a (No package metadata was found for libusb-package)
[DEBUG] (smbus) (find_devices): searching LinuxI2c
[DEBUG] (smbus) (find_devices): LinuxI2c drivers: Ddr4Temperature, EvgaPascal, RogTuring, VengeanceRgb
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-3
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-1
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-6
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-4
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-2
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-0
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-7
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0008 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-5
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: Aquacomputer, AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 048d:8297 (usage_page=0xff89 usage=0x0010)
[DEBUG] (usb) (find_devices): HID device: 048d:8297 (usage_page=0xff89 usage=0x00cc)
[DEBUG] (usb) (probe): RgbFusion2 identified: Gigabyte RGB Fusion 2.0 8297 Controller
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c0b (usage_page=0xffc0 usage=0x0001)
[DEBUG] (usb) (probe): CommanderPro identified: Corsair Lighting Node Pro
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c17 (usage_page=0xff00 usage=0x0001)
[DEBUG] (hydro_platinum) (probe): HydroPlatinum identified: Corsair Hydro H115i Platinum
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c10 (usage_page=0x0084 usage=0x0052)
[DEBUG] (usb) (__init__): has kernel driver: corsair-cpro (/sys/class/hidraw/hidraw6/device/hwmon/hwmon4)
[DEBUG] (usb) (probe): CommanderPro identified: Corsair Commander Pro
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 248a:8368 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1b1c:1b49
[DEBUG] (usb) (find_devices): USB device: 248a:8368
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 8087:0029
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c10
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c17
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c0b
[DEBUG] (usb) (find_devices): USB device: 05e3:0610
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 048d:8297
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (cli) (main): device: Gigabyte RGB Fusion 2.0 8297 Controller
[DEBUG] (usb) (send_feature_report): sending feature report 0xcc with 63 bytes: 60:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (get_feature_report): got feature report 0x00 with 63 bytes: 01:00:01:01:00:06:00:00:00:00:00:49:54:38:32:39:37:42:58:2d:47:42:58:35:37:30:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:02:00:02:01:00:00:00:01:02:00:00:01:97:82:00:00:00:00
Gigabyte RGB Fusion 2.0 8297 Controller
├── Hardware name       IT8297BX-GBX570
└── Firmware version            1.0.6.0

[DEBUG] (cli) (main): device: Corsair Lighting Node Pro
[DEBUG] (keyval) (__init__): data in /run/user/1000/liquidctl/vid1b1c_pid0c0b/loc5
[DEBUG] (usb) (clear_enqueued_reports): discarded 0 previously enqueued reports
[DEBUG] (usb) (write): writting report 0x00 with 64 bytes: 02:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (read): read 16 bytes: 00:00:0a:04:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (clear_enqueued_reports): discarded 0 previously enqueued reports
[DEBUG] (usb) (write): writting report 0x00 with 64 bytes: 06:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (read): read 16 bytes: 00:03:00:00:00:00:00:00:00:00:00:00:00:00:00:00
Corsair Lighting Node Pro
├── Firmware version      0.10.4
└── Bootloader version       3.0

[DEBUG] (cli) (main): device: Corsair Hydro H115i Platinum
[DEBUG] (keyval) (__init__): data in /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2
[DEBUG] (keyval) (store): stored leds_enabled=0 (in /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2/leds_enabled)
[DEBUG] (keyval) (store): stored pump_mode=1 (in /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2/pump_mode)
[DEBUG] (keyval) (load): loaded pump_mode=1 (from /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2/pump_mode)
[DEBUG] (keyval) (load): no data (file) found for fan1_mode
[DEBUG] (hydro_platinum) (_missing_): falling back to FIXED_DUTY for _FanMode(None)
[DEBUG] (keyval) (load): no data (file) found for fan1_duty
[INFO] (hydro_platinum) (_generate_cooling_payload): setting fan1 to 100% duty cycle
[DEBUG] (keyval) (load): no data (file) found for fan2_mode
[DEBUG] (hydro_platinum) (_missing_): falling back to FIXED_DUTY for _FanMode(None)
[DEBUG] (keyval) (load): no data (file) found for fan2_duty
[INFO] (hydro_platinum) (_generate_cooling_payload): setting fan2 to 100% duty cycle
[INFO] (hydro_platinum) (_send_set_cooling): setting pump mode to balanced
[DEBUG] (keyval) (load_store): loaded sequence=7 (from /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2/sequence)
[DEBUG] (keyval) (load_store): replaced with sequence=8 (stored in /run/user/1000/liquidctl/vid1b1c_pid0c17/loc2/sequence)
[DEBUG] (usb) (clear_enqueued_reports): discarded 0 previously enqueued reports
[DEBUG] (usb) (write): writting report 0x00 with 64 bytes: 3f:40:14:00:ff:05:ff:ff:ff:ff:ff:02:00:00:00:00:ff:02:00:00:00:00:ff:01:00:00:00:00:00:07:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:fd
[INFO] (cli) (log): detailed error: unexpected OS error with Corsair Hydro H115i Platinum: OSError('Could not write to device')
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/liquidctl/cli.py", line 460, in main
    status = dev.initialize(**opts)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/hydro_platinum.py", line 214, in initialize
    res = self._send_set_cooling()
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/hydro_platinum.py", line 422, in _send_set_cooling
    return self._send_command(_FEATURE_COOLING, _CMD_SET_COOLING, data=data)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/hydro_platinum.py", line 379, in _send_command
    self.device.write(buf)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/usb.py", line 480, in write
    raise OSError('Could not write to device')
OSError: Could not write to device
[ERROR] (cli) (log): unexpected OS error with Corsair Hydro H115i Platinum: OSError('Could not write to device')
[DEBUG] (cli) (main): device: Corsair Commander Pro
[DEBUG] (keyval) (__init__): data in /run/user/1000/liquidctl/vid1b1c_pid0c10/loc6
[INFO] (commander_pro) (initialize): bound to corsair-cpro kernel driver, assuming it is already initialized
[WARNING] (commander_pro) (_get_static_info_from_hwmon): some attributes cannot be read from corsair-cpro kernel driver
[DEBUG] (commander_pro) (_get_static_info_from_hwmon): [1, 1, 1, 1]
[DEBUG] (keyval) (store): stored temp_sensors_connected=[1, 1, 1, 1] (in /run/user/1000/liquidctl/vid1b1c_pid0c10/loc6/temp_sensors_connected)
[DEBUG] (hwmon) (get_string): read fan1_label: fan1 4pin
[DEBUG] (hwmon) (get_string): read fan2_label: fan2 4pin
[DEBUG] (hwmon) (get_string): read fan3_label: fan3 4pin
[DEBUG] (hwmon) (get_string): read fan4_label: fan4 4pin
[DEBUG] (commander_pro) (_get_static_info_from_hwmon): [2, 2, 2, 2, 0, 0]
[DEBUG] (keyval) (store): stored fan_modes=[2, 2, 2, 2, 0, 0] (in /run/user/1000/liquidctl/vid1b1c_pid0c10/loc6/fan_modes)
Corsair Commander Pro
├── Temperature probe 1    Yes
├── Temperature probe 2    Yes
├── Temperature probe 3    Yes
├── Temperature probe 4    Yes
├── Fan 1 control mode     PWM
├── Fan 2 control mode     PWM
├── Fan 3 control mode     PWM
├── Fan 4 control mode     PWM
├── Fan 5 control mode     N/A
└── Fan 6 control mode     N/A

### Affected device

Corsair Hydro H115i RGB Platinum

### Operating system and version

Arch Linux

### Installation method

AUR

### Version of liquidctl

liquidctl v1.11.1 (Linux-6.0.12-arch1-1-x86_64-with-glibc2.36)

**Comment by HeathenHacks** [comment]
Not sure if I should mark this as closed or not, but after numerous reboots (because of multi-monitor problems), the issue with my AIO seemed to have been fixed.

**Comment by jonasmalacofilho** [comment]
That's odd. Please let me know if the issue comes back.
