### ISSUE TITLE
Python library: set_color should accept tuple for single color

### ISSUE THREAD

**Issue by henryruhs** [liquidctl/liquidctl#574]
Current API:

```python
device.set_color('sync', 'fixed', [ (255, 255, 255) ])
```

Suggested API:

```python
device.set_color('sync', 'fixed', (255, 255, 255))
```

**Comment by jonasmalacofilho** [comment]
This isn't feasible without significant a prior rework of how the drivers are implemented, which is indeed needed but not something the project has the bandwidth to do right now.[^1]

Without that prior rework, each driver would need to be modified to accept this new possible type for `colors`, and that would be sacrificing too much maintainability for a tiny and only occasional benefit in ergonomics.

For now I'll archive the idea, but it's something we can revisit once/if that rework is done.

[^1]: https://github.com/liquidctl/liquidctl/issues/569
