### ISSUE TITLE
AttributeError: 'sys.flags' object has no attribute 'utf8_mode' on python 3.6.8 (RHEL8)

### ISSUE THREAD

**Issue by jalapenopuzzle** [liquidctl/liquidctl#588]
### Describe the bug

When I run (almost) any `liquidctl` command on RHEL 8.6, the following error message is produced:
```bash
[user@rhel8 ~]$ ~/.local/bin/liquidctl initialize
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
[user@rhel8 ~]$
```
I am using liquidctl 1.12.1.

It appears that this is caused by:
liquidctl/cli.py:311-312
```python
    _LOGGER.debug('encoding: %s default, %s preferred, utf8_mode %s',
                  locale.getdefaultlocale()[1], locale.getpreferredencoding(), sys.flags.utf8_mode)
```
The flag `sys.flags.utf8_mode` was introduced in python 3.7 <https://docs.python.org/3/library/sys.html#sys.flags>, but I am using python 3.6.8 as supplied with RHEL8.
I see that you require python 3.7 in the list of dependencies in README.md, but commenting out these logger lines appears to allow liquidctl to work on RHEL8. I am able to initialise and see status of my Corsair Commander Core.

I haven't investigated installing a newer python on RHEL8 to support running `liquidctl`. For the moment I'm running fine on python 3.6.8 (after commenting out the logging line).

## Installation Method
```
dnf install python3 python3-pip python3-setuptools python3-pyusb python3-colorlog python3-docopt libusbx-devel python3-pytest python3-pyudev systemd-libs python3-Cython python3-devel systemd-devel
```
These are needed for pip to build pillow (it seems the rpm python3-pillow is not good enough):
```
dnf install libjpeg-turbo-devel turbojpeg-devel openjpeg2-devel zlib-devel libtiff-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel harfbuzz-devel fribidi-devel libraqm-devel libimagequant-devel libxcb-devel
```
And then
```
pip3 install --user liquidctl
```

### Commands executed

```
[user@rhel8 ~]$ ~/.local/bin/liquidctl initialize
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
[user@rhel8 ~]$
```

### Output of all relevant commands with `--debug` flag

```
[user@rhel8 ~]$ ~/.local/bin/liquidctl initialize --debug
[DEBUG] (cli) (_log_env_infos): script: /home/stanb/.local/bin/liquidctl
[DEBUG] (cli) (_log_env_infos): version: 1.12.1
[DEBUG] (cli) (_log_env_infos): platform: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-redhat-8.6-Ootpa
[DEBUG] (cli) (_log_env_infos): python: 3.6.8 (default, Jan 14 2022, 11:04:20)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]
Traceback (most recent call last):
  File "/home/user/.local/bin/liquidctl", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/liquidctl/cli.py", line 402, in main
    _log_env_infos()
  File "/home/user/.local/lib/python3.6/site-packages/liquidctl/cli.py", line 312, in _log_env_infos
    locale.getdefaultlocale()[1], locale.getpreferredencoding(), sys.flags.utf8_mode)
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
[user@rhel8 ~]$
```

### Affected device

<none>

### Operating system and version

RHEL 8.6

### Installation method

See text above for installation method

### Version of liquidctl

liquidctl v1.12.1 (Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-redhat-8.6-Ootpa)

**Comment by jonasmalacofilho** [comment]
Thanks for the report.

That said, and even though it would seem like a minor change, I'm not going to reintroduce support Python 3.6 here: there are some other issues with Python 3.6 (especially when non-UTF-8 locales are used), plus the overhead of supporting one additional Python version.

In fact, Python 3.7 is about to reach its end-of-life, and will also soon be dropped from being (officially) supported by liquidctl.
