### ISSUE TITLE
Emty list

### ISSUE THREAD

**Issue by maxreitner** [liquidctl/liquidctl#646]
### Describe the bug

I get no devices shown in my list

### Commands executed

liquidctl list

### Output of all relevant commands with `--debug` flag

    <details> 
        <summary>liquidctl list --debug</summary> 
[DEBUG] (cli) (_log_env_infos): script: /usr/bin/liquidctl
[DEBUG] (cli) (_log_env_infos): version: 1.13.0
[DEBUG] (cli) (_log_env_infos): platform: Linux-6.6.2-arch1-1-x86_64-with-glibc2.38
[DEBUG] (cli) (_log_env_infos): python: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
[DEBUG] (cli) (_log_env_infos): encoding: UTF-8 current, UTF-8 preferred, utf8_mode 0
[DEBUG] (cli) (_log_env_infos): with colorlog: 6.7.0
[DEBUG] (cli) (_log_env_infos): with crcmod: 1.7
[DEBUG] (cli) (_log_env_infos): with docopt: 0.6.2
[DEBUG] (cli) (_log_env_infos): with hidapi: 0.14.0
[DEBUG] (cli) (_log_env_infos): with pyusb: 1.2.1
[DEBUG] (cli) (_log_env_infos): with pillow: 10.1.0
[DEBUG] (cli) (_log_env_infos): with smbus: 1.1
[DEBUG] (cli) (_log_env_infos): with winusbcdc: version n/a (No package metadata was found for winusbcdc)
[DEBUG] (cli) (_log_env_infos): with libusb-package: version n/a (No package metadata was found for libusb-package)
[DEBUG] (smbus) (find_devices): searching LinuxI2c
[DEBUG] (smbus) (find_devices): LinuxI2c drivers: Ddr4Temperature, EvgaPascal, RogTuring, VengeanceRgb
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-3
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-10
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-1
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-17
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-8
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-15
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-6
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-13
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-4
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-11
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-2
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-0
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-9
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-16
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-7
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-14
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-5
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-12
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: Aquacomputer, AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 056a:033c (usage_page=0xff0d usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 056a:033c (usage_page=0xff00 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 056a:033c (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 056a:033c (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 042e:ac0b (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 042e:ac0a (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1462:7d89 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1462:7d89 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1e71:300e (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 0db0:6c09 (usage_page=0xffc0 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0059 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0059 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0059 usage=0x0020)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0059 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0059 usage=0x0050)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0059 usage=0x0060)
[DEBUG] (usb) (find_devices): HID device: 1532:024e (usage_page=0x0059 usage=0x0070)
[DEBUG] (usb) (find_devices): HID device: 046d:0a15 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1e7d:2e22 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1e7d:2e22 (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1e7d:2e22 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1e7d:2e22 (usage_page=0x000a usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1e7d:2e22 (usage_page=0x000b usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1e7d:2e22 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 0bda:0411
[DEBUG] (usb) (find_devices): USB device: 0bda:0411
[DEBUG] (usb) (find_devices): USB device: 05e3:0625
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1e7d:2e22
[DEBUG] (usb) (find_devices): USB device: 046d:0a15
[DEBUG] (usb) (find_devices): USB device: 1532:024e
[DEBUG] (usb) (find_devices): USB device: 8087:0033
[DEBUG] (usb) (find_devices): USB device: 0db0:6c09
[DEBUG] (usb) (find_devices): USB device: 1e71:300e
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 1462:7d89
[DEBUG] (usb) (find_devices): USB device: 042e:ac0a
[DEBUG] (usb) (find_devices): USB device: 042e:ac0b
[DEBUG] (usb) (find_devices): USB device: 05e3:0610
[DEBUG] (usb) (find_devices): USB device: 056a:033c
[DEBUG] (usb) (find_devices): USB device: 0bda:5411
[DEBUG] (usb) (find_devices): USB device: 0bda:5411
[DEBUG] (usb) (find_devices): USB device: 05e3:0610
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002

    </details>     

    <details> 
        <summary>lsusb -vt</summary> 
 /:  Bus 001.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/16p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 001: Dev 002, If 0, Class=Hub, Driver=hub/4p, 480M
        ID 05e3:0610 Genesys Logic, Inc. Hub
        |__ Port 002: Dev 004, If 0, Class=Hub, Driver=hub/5p, 480M
            ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
            |__ Port 001: Dev 006, If 0, Class=Hub, Driver=hub/4p, 480M
                ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
                |__ Port 002: Dev 009, If 0, Class=Human Interface Device, Driver=usbhid, 12M
                    ID 056a:033c Wacom Co., Ltd CTH-490 [Intuos Art/Photo/Comic (S)]
                |__ Port 002: Dev 009, If 1, Class=Human Interface Device, Driver=usbhid, 12M
                    ID 056a:033c Wacom Co., Ltd CTH-490 [Intuos Art/Photo/Comic (S)]
                |__ Port 002: Dev 009, If 2, Class=Human Interface Device, Driver=usbhid, 12M
                    ID 056a:033c Wacom Co., Ltd CTH-490 [Intuos Art/Photo/Comic (S)]
            |__ Port 004: Dev 008, If 0, Class=Hub, Driver=hub/2p, 480M
                ID 05e3:0610 Genesys Logic, Inc. Hub
                |__ Port 001: Dev 011, If 0, Class=Human Interface Device, Driver=usbhid, 12M
                    ID 042e:ac0b Acer, Inc. 
                |__ Port 002: Dev 013, If 0, Class=Human Interface Device, Driver=usbhid, 12M
                    ID 042e:ac0a Acer, Inc. 
    |__ Port 002: Dev 003, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1532:024e Razer USA, Ltd 
    |__ Port 002: Dev 003, If 1, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1532:024e Razer USA, Ltd 
    |__ Port 002: Dev 003, If 2, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1532:024e Razer USA, Ltd 
    |__ Port 002: Dev 003, If 3, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1532:024e Razer USA, Ltd 
    |__ Port 002: Dev 003, If 4, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1532:024e Razer USA, Ltd 
    |__ Port 003: Dev 005, If 0, Class=Audio, Driver=snd-usb-audio, 12M
        ID 046d:0a15 Logitech, Inc. G35 Headset
    |__ Port 003: Dev 005, If 1, Class=Audio, Driver=snd-usb-audio, 12M
        ID 046d:0a15 Logitech, Inc. G35 Headset
    |__ Port 003: Dev 005, If 2, Class=Audio, Driver=snd-usb-audio, 12M
        ID 046d:0a15 Logitech, Inc. G35 Headset
    |__ Port 003: Dev 005, If 3, Class=Human Interface Device, Driver=usbhid, 12M
        ID 046d:0a15 Logitech, Inc. G35 Headset
    |__ Port 004: Dev 007, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1e7d:2e22 ROCCAT Kone XTD Mouse
    |__ Port 004: Dev 007, If 1, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1e7d:2e22 ROCCAT Kone XTD Mouse
    |__ Port 010: Dev 010, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        ID 1462:7d89 Micro Star International 
    |__ Port 011: Dev 012, If 0, Class=Hub, Driver=hub/4p, 480M
        ID 05e3:0608 Genesys Logic, Inc. Hub
        |__ Port 003: Dev 015, If 0, Class=Vendor Specific Class, Driver=[none], 480M
            ID 1e71:300e NZXT 
        |__ Port 003: Dev 015, If 1, Class=Human Interface Device, Driver=usbhid, 480M
            ID 1e71:300e NZXT 
    |__ Port 013: Dev 014, If 0, Class=Audio, Driver=snd-usb-audio, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 013: Dev 014, If 1, Class=Audio, Driver=snd-usb-audio, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 013: Dev 014, If 2, Class=Audio, Driver=snd-usb-audio, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 013: Dev 014, If 3, Class=Audio, Driver=snd-usb-audio, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 013: Dev 014, If 4, Class=Audio, Driver=snd-usb-audio, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 013: Dev 014, If 5, Class=Audio, Driver=snd-usb-audio, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 013: Dev 014, If 6, Class=Audio, Driver=snd-usb-audio, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 013: Dev 014, If 7, Class=Human Interface Device, Driver=usbhid, 480M
        ID 0db0:6c09 Micro Star International 
    |__ Port 014: Dev 016, If 0, Class=Wireless, Driver=btusb, 12M
        ID 8087:0033 Intel Corp. AX211 Bluetooth
    |__ Port 014: Dev 016, If 1, Class=Wireless, Driver=btusb, 12M
        ID 8087:0033 Intel Corp. AX211 Bluetooth
/:  Bus 002.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/9p, 20000M/x2
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    |__ Port 002: Dev 002, If 0, Class=Hub, Driver=hub/4p, 10000M
        ID 05e3:0625 Genesys Logic, Inc. 
        |__ Port 002: Dev 003, If 0, Class=Hub, Driver=hub/3p, 5000M
            ID 0bda:0411 Realtek Semiconductor Corp. Hub
            |__ Port 001: Dev 004, If 0, Class=Hub, Driver=hub/2p, 5000M
                ID 0bda:0411 Realtek Semiconductor Corp. Hub
/:  Bus 003.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/1p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
/:  Bus 004.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/1p, 20000M/x2
    ID 1d6b:0003 Linux Foundation 3.0 root hub

    </details>     

### Affected device

NZXT Kraken 240, 2023, Model: RL-KN240-B1, EAN: 5056547202600

### Operating system and version

Arch Linux x86_64

### Installation method

sudo pacman -S liquidctl

### Version of liquidctl

liquidctl v1.13.0 (Linux-6.6.2-arch1-1-x86_64-with-glibc2.38)

**Comment by aleksamagicka** [comment]
> NZXT Kraken 240, 2023, Model: RL-KN240-B1, EAN: 5056547202600

Support for it in liquidctl has been merged just [last month](https://github.com/liquidctl/liquidctl/commit/846ac5f5aa9d5484e8ed1d549fd2478bbf51fdd8) and [v1.13.0](https://github.com/liquidctl/liquidctl/releases/tag/v1.13.0) is from July. Generally, please refer to the [compatibility table](https://github.com/liquidctl/liquidctl#supported-devices). You'll have to use the [Git version](https://github.com/liquidctl/liquidctl#installing-from-pypi-or-github) for the time being.

See #641 for a similar issue.

**Comment by maxreitner** [comment]
that worked, i just installed the git version and added the udev rules and rebooted, thanks alot!
