### ISSUE TITLE
Proposal: remove experimental note and associated description suffix

### ISSUE THREAD

**Issue by jonasmalacofilho** [liquidctl/liquidctl#662]
In the early days of the project I thought it was important to communicate to our users how well they could expect a device to work with liquidctl. This was done, for new or still unstable devices, with an `e`/experimental note (in the supported devices table) and an `(experimental)` suffix in their description.

I'm not sure it makes sense to do that anymore:

- we have many more drivers, supported devices, and contributors, and so our capability to _accurately_ gauge that, across all configurations, use cases, firmware versions, etc, has likely degraded;
- our development pace has reduced substantially, degrading the temporal resolution (and, thus, accuracy) of any such claim;
- and, on the other hand, _most_ drivers either work well from the start or have quickly and easily been fixed.

That said, we have a few devices that are essentially long-term broken. IIRC, they are those from the Commander Core and Kraken 2023 families, all due to firmware changes. It probably would be nice to communicate _that_ to our users, in place of the current experimental tags.

Comments?

**Comment by aleksamagicka** [comment]
> and, on the other hand, most drivers either work well from the start or have quickly and easily been fixed.

Huh, was just pondering this a few days ago in the same context. I endorse the outlined plan.
