### ISSUE TITLE
Input power curve for HX1500i is absurd

### ISSUE THREAD

**Issue by yshui** [liquidctl/liquidctl#675]
### Describe the bug

I know the comment says the curve is not accurate for 2~10%. But it's much worse than that. For 230V input voltage, if I plug in output power of 750W, I got input power of 39866.7W (!). An efficiency of 1.88% !

### Commands executed

`liquidctl status`

### Output of all relevant commands with `--debug` flag

N/A

### Affected device

Corsair HX1500i

### Does your version of liquidctl support the device in question?

Yes, my version supports it

### Operating system and version

NixOS

### Installation method

nixpkgs

### Version of liquidctl

liquidctl v1.13.0 (Linux-6.7.5-lqx1-x86_64-with-glibc2.38)

**Comment by yshui** [comment]
Plot of the power curve for 230V

![plot](https://github.com/liquidctl/liquidctl/assets/366851/cb489e51-fbb4-4f2f-9988-e57323ed75fc)

**Comment by jonasmalacofilho** [comment]
Yeap, that's wrong.

Can you give #676 a try? I recomputed the curves and I think they're sensible now.

For reference, here're the new input power and efficiency curves for the HX1500i at 230 V:

![new_hx1500i_230v_input_curve](https://github.com/liquidctl/liquidctl/assets/1832496/d21ddf93-a247-4a94-a413-1a90d0190be8)

**Comment by yshui** [comment]
Looks much more reasonable now. Thanks!
