### ISSUE TITLE
ZOTAC GAMING GeForce RTX 4080 SUPER Trinity OC

### ISSUE THREAD

**Issue by makhlouta** [liquidctl/liquidctl#710]
### Device type

GPU

### Product page

https://www.zotac.com/us-store/product/graphics_card/zotac-gaming-geforce-rtx-4080-super-trinity-oc-white-edition-16gb-gddr6x

### First-party software

FireStorm

### What monitoring functionality does the device support?

temperatures, fan/pump speeds or duty cycles

### What configuration functionality does the device support?

lighting of embedded LEDs

### Physical connection

PCI-e

### Additional information about the device

01:00.0 VGA compatible controller: NVIDIA Corporation AD103 [GeForce RTX 4080 SUPER] (rev a1) (prog-if 00 [VGA controller])
        Subsystem: ZOTAC International (MCO) Ltd. Device 4702
        Flags: bus master, fast devsel, latency 0, IRQ 123, IOMMU group 13
        Memory at f5000000 (32-bit, non-prefetchable) [size=16M]
        Memory at f800000000 (64-bit, prefetchable) [size=16G]
        Memory at fc00000000 (64-bit, prefetchable) [size=32M]
        I/O ports at f000 [size=128]
        Expansion ROM at f6000000 [virtual] [disabled] [size=512K]
        Capabilities: <access denied>
        Kernel driver in use: nvidia
        Kernel modules: nouveau, nvidia_drm, nvidia

01:00.1 Audio device: NVIDIA Corporation Device 22bb (rev a1)
        Subsystem: ZOTAC International (MCO) Ltd. Device 4702
        Flags: bus master, fast devsel, latency 0, IRQ 119, IOMMU group 13
        Memory at f6080000 (32-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

i2c-2   i2c             NVIDIA i2c adapter 1 at 1:00.0          I2C adapter
i2c-3   i2c             NVIDIA i2c adapter 2 at 1:00.0          I2C adapter
i2c-4   i2c             NVIDIA i2c adapter 3 at 1:00.0          I2C adapter
i2c-5   i2c             NVIDIA i2c adapter 4 at 1:00.0          I2C adapter
i2c-6   i2c             NVIDIA i2c adapter 5 at 1:00.0          I2C adapter
i2c-7   i2c             NVIDIA i2c adapter 6 at 1:00.0          I2C adapter

### Can you help with implementing or testing the changes needed for liquidctl to support this device?

YES

**Comment by jonasmalacofilho** [comment]
More GPUs are not planned for now. But thanks for the suggestion.
