### ISSUE TITLE
Cannot use new NZXT Controller for changing colors

### ISSUE THREAD

**Issue by Displace5158** [liquidctl/liquidctl#721]
### Describe the bug

![Screenshot_20240702_110538](https://github.com/liquidctl/liquidctl/assets/59393682/a56ab0f1-be16-4897-a371-18628d701825)
For some reason I cannot use my controller for changing colors, setting fans speed works tho. I read in the documentation that should support this feature. I'm extremely new to Linux (I use Fedora 40 with KDE), so if I made a stupid mistake, tell me.

### Commands executed

sudo liquidctl set sync color fixed ff0000

### Output of all relevant commands with `--debug` flag

[DEBUG] (cli) (_log_env_infos): script: /usr/bin/liquidctl
[DEBUG] (cli) (_log_env_infos): version: 1.13.0
[DEBUG] (cli) (_log_env_infos): platform: Linux-6.9.4-200.fc40.x86_64-x86_64-with-glibc2.39
[DEBUG] (cli) (_log_env_infos): python: 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)]
[DEBUG] (cli) (_log_env_infos): encoding: UTF-8 current, UTF-8 preferred, utf8_mode 0
[DEBUG] (cli) (_log_env_infos): with colorlog: 6.8.2
[DEBUG] (cli) (_log_env_infos): with crcmod: 1.7
[DEBUG] (cli) (_log_env_infos): with docopt: 0.6.2
[DEBUG] (cli) (_log_env_infos): with hidapi: 0.14.0
[DEBUG] (cli) (_log_env_infos): with pyusb: 1.2.1
[DEBUG] (cli) (_log_env_infos): with pillow: 10.3.0
[DEBUG] (cli) (_log_env_infos): with smbus: 1.1
[DEBUG] (cli) (_log_env_infos): with winusbcdc: version n/a (No package metadata was found for winusbcdc)
[DEBUG] (cli) (_log_env_infos): with libusb-package: version n/a (No package metadata was found for libusb-package)
[DEBUG] (smbus) (find_devices): searching LinuxI2c
[DEBUG] (smbus) (find_devices): LinuxI2c drivers: Ddr4Temperature, EvgaPascal, RogTuring, VengeanceRgb
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-3
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-10
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-1
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-8
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-6
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-13
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-4
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-11
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-2
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-0
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-9
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-7
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-14
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-5
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-12
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: Aquacomputer, AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:0099 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0004)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0024)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x001a)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0010)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0012)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x001e)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0016)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x001a)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x001c)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0018)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0x0084 usage=0x0020)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0xffff usage=0x00fe)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0xffff usage=0x00ff)
[DEBUG] (usb) (find_devices): HID device: 0665:5161 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1e71:300c (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1e71:2019 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (__init__): has kernel driver: nzxt-smart2 (/sys/class/hidraw/hidraw12/device/hwmon/hwmon3)
[DEBUG] (usb) (probe): SmartDevice2 identified: NZXT RGB & Fan Controller (3+6 channels) (experimental)
[DEBUG] (usb) (find_devices): HID device: 1462:7d93 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1462:7d93 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:0c02 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 145f:0250 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 145f:0250 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 145f:0250 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 145f:0250 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 145f:0250 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 145f:0250 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 145f:0250 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:0517 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0517 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 174c:3074
[DEBUG] (usb) (find_devices): USB device: 05e3:0626
[DEBUG] (usb) (find_devices): USB device: 045b:0210
[DEBUG] (usb) (find_devices): USB device: 045b:0210
[DEBUG] (usb) (find_devices): USB device: 045b:0210
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 174c:2074
[DEBUG] (usb) (find_devices): USB device: 1532:0517
[DEBUG] (usb) (find_devices): USB device: 145f:0250
[DEBUG] (usb) (find_devices): USB device: 1532:0c02
[DEBUG] (usb) (find_devices): USB device: 8087:0033
[DEBUG] (usb) (find_devices): USB device: 1462:7d93
[DEBUG] (usb) (find_devices): USB device: 1e71:2019
[DEBUG] (usb) (find_devices): USB device: 1e71:300c
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 0665:5161
[DEBUG] (usb) (find_devices): USB device: 05e3:0610
[DEBUG] (usb) (find_devices): USB device: 045b:0209
[DEBUG] (usb) (find_devices): USB device: 045b:0209
[DEBUG] (usb) (find_devices): USB device: 045b:0209
[DEBUG] (usb) (find_devices): USB device: 1532:0099
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (cli) (main): device: NZXT RGB & Fan Controller (3+6 channels) (experimental)
[INFO] (cli) (log): detailed error: NZXT RGB & Fan Controller (3+6 channels) (experimental): operation not supported by the device: NotSupportedByDevice()
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/liquidctl/cli.py", line 477, in main
    _device_set_color(dev, args, **opts)
  File "/usr/lib/python3.12/site-packages/liquidctl/cli.py", line 284, in _device_set_color
    dev.set_color(args['<channel>'].lower(), args['<mode>'].lower(), color, **opts)
  File "/usr/lib/python3.12/site-packages/liquidctl/driver/smart_device.py", line 152, in set_color
    raise NotSupportedByDevice()
liquidctl.error.NotSupportedByDevice: operation not supported by the device
[ERROR] (cli) (log): NZXT RGB & Fan Controller (3+6 channels) (experimental): operation not supported by the device

### Affected device

NZXT RBG & FAN controller

### Does your version of liquidctl support the device in question?

Yes, my version supports it

### Operating system and version

Linux Fedora 40

### Installation method

sudo dnf install liquidctl

### Version of liquidctl

liquidctl v1.13.0 (Linux-6.9.4-200.fc40.x86_64-x86_64-with-glibc2.39)

**Comment by aleksamagicka** [comment]
Setting colors is [not supported](https://github.com/liquidctl/liquidctl/blob/main/liquidctl/driver/smart_device.py#L437) for your variant (product ID `0x2019`). #541 should be tracking that.
