### ISSUE TITLE
Commander Core XT flashing lights

### ISSUE THREAD

**Issue by Devin3501** [liquidctl/liquidctl#727]
Recently installed a Corsair Commander Core XT into my tower and now have a problem where every couple seconds the RGBs flash on and off. Went through troubleshooting with some knowledgeable guys and we couldnt get CoolerControl or OpenRGB or anything to detect RGB control in them. One of them told me to create an issue on here to see if i could get some better answers to my issue. Appreciate you guys!

**Comment by jonasmalacofilho** [comment]
This is a known limitation: https://github.com/liquidctl/liquidctl/issues/448
