### ISSUE TITLE
Please add support to MasterLiquid 360 Atmos

### ISSUE THREAD

**Issue by eaviti** [liquidctl/liquidctl#736]
### Device type

MasterLiquid 360 Atmos

### Product page

https://www.coolermaster.com/en-eu/products/masterliquid-360-atmos/

### First-party software

MasterCRTL

### What monitoring functionality does the device support?

temperatures, fan/pump speeds or duty cycles

### Physical connection

AIO Header

**Comment by jonasmalacofilho** [comment]
Hi there.

You mentioned that the device is only connected to a standard (motherboard?) AIO header.

In that case, it cannot be directly controlled; instead, programs like liquidctl need to support the device on the other end of that cable, i.e. your motherboard. And motherboard fan control is outside the (current) scope of this project.

Sorry about that.
