### ISSUE TITLE
Corsair iCUE H150i Elite RGB (White) has support in the documentation, but my liquidctl doesn't find it

### ISSUE THREAD

**Issue by weversonl** [liquidctl/liquidctl#741]
### Describe the bug

I installed my water cooler, Corsair iCUE H150i Elite RGB (White)
But when I try to use liquidctl, it doesn't find it.

I've already placed it in the CPU FAN slot on the motherboard, in the AIO Pump slot, but it still isn't recognized.
However, in Windows' ICUE, it recognizes it normally, regardless of which slot I have fitted, AIO pump or CPU Fan.

I saw that in the source code, it mentions having support:

https://github.com/liquidctl/liquidctl/blob/7637f173be167daeb1a2a21fd4fb0a9dd217d158/liquidctl/driver/hydro_platinum.py#L138C1-L139C45

### Commands executed

❯ liquidctl list          
Device #0: ASUS Aura LED Controller

### Output of all relevant commands with `--debug` flag

❯ liquidctl --debug list  

[DEBUG] (cli) (_log_env_infos): script: /usr/bin/liquidctl
[DEBUG] (cli) (_log_env_infos): version: 1.13.0
[DEBUG] (cli) (_log_env_infos): platform: Linux-6.11.5-arch1-1-x86_64-with-glibc2.40
[DEBUG] (cli) (_log_env_infos): python: 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
[DEBUG] (cli) (_log_env_infos): encoding: UTF-8 current, UTF-8 preferred, utf8_mode 0
[DEBUG] (cli) (_log_env_infos): with colorlog: 6.8.2
[DEBUG] (cli) (_log_env_infos): with crcmod: 1.7
[DEBUG] (cli) (_log_env_infos): with docopt: 0.6.2
[DEBUG] (cli) (_log_env_infos): with hidapi: 0.14.0
[DEBUG] (cli) (_log_env_infos): with pyusb: 1.2.1
[DEBUG] (cli) (_log_env_infos): with pillow: 11.0.0
[DEBUG] (cli) (_log_env_infos): with smbus: 1.1
[DEBUG] (cli) (_log_env_infos): with winusbcdc: version n/a (No package metadata was found for winusbcdc)
[DEBUG] (cli) (_log_env_infos): with libusb-package: version n/a (No package metadata was found for libusb-package)
[DEBUG] (smbus) (find_devices): searching LinuxI2c
[DEBUG] (smbus) (find_devices): LinuxI2c drivers: Ddr4Temperature, EvgaPascal, RogTuring, VengeanceRgb
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-3
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-10
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-1
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-8
[DEBUG] (smbus) (find_devices): I²C adapter: 10-0036 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-6
[DEBUG] (smbus) (find_devices): I²C adapter: 10-0052 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-4
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-11
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-2
[DEBUG] (smbus) (find_devices): I²C adapter: 12-0053 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-0
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-9
[DEBUG] (smbus) (find_devices): I²C adapter: 10-0037 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-7
[DEBUG] (smbus) (find_devices): I²C adapter: 10-0053 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-5
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-12
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: Aquacomputer, AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 0b05:1939 (usage_page=0xff72 usage=0x00a1)
[DEBUG] (usb) (probe): AuraLed identified: ASUS Aura LED Controller
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c41 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 05ac:024f (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 05ac:024f (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 05ac:024f (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 05ac:024f (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 05ac:024f (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 05ac:024f (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 05ac:024f (usage_page=0xffff usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:007e (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:007b (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0x000b usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff43 usage=0x0202)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x000c)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0x0001 usage=0x003a)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0xff00 usage=0x000c)
[DEBUG] (usb) (find_devices): HID device: 046d:0ab5 (usage_page=0x0001 usage=0x003a)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (find_devices): USB device: 05e3:0626
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 046d:0ab5
[DEBUG] (usb) (find_devices): USB device: 045e:02fe
[DEBUG] (usb) (find_devices): USB device: 1532:007b
[DEBUG] (usb) (find_devices): USB device: 1532:007e
[DEBUG] (usb) (find_devices): USB device: 0451:2046
[DEBUG] (usb) (find_devices): USB device: 05ac:024f
[DEBUG] (usb) (find_devices): USB device: 05e3:0610
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 0781:55ab
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c41
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 0b05:1939
[DEBUG] (usb) (find_devices): USB device: 0781:5567
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
Device #0: ASUS Aura LED Controller
├── Vendor ID: 0x0b05
├── Product ID: 0x1939
├── Release number: 0x0100
├── Serial number: 9876543210
├── Bus: hid
├── Address: /dev/hidraw0
└── Driver: AuraLed
[DEBUG] (cli) (_list_devices_human): MRO: AuraLed, UsbHidDriver, BaseUsbDriver, BaseDriver, object

### Affected device

Corsair iCUE H150i Elite RGB (White)

### Does your version of liquidctl support the device in question?

Yes, my version supports it

### Operating system and version

ArchLinux (6.11.5-arch1-1)

### Installation method

pacman (Arch official)

### Version of liquidctl

liquidctl v1.13.0 (Linux-6.11.5-arch1-1-x86_64-with-glibc2.40)

**Comment by aleksamagicka** [comment]
That was added about 2 months ago and isn't in liquidctl 1.13.0; you'll
need to install liquidctl from Git. There are instructions in the README
(sorry, on phone and can't link directly).
